name: 'Terraform GitHub Actions'
on:
  push:
    branches:
    - main
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_VAR_billing_account : ${{ secrets.BILLING_ACCOUNT }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - id: gcloud
        name: 'GCloud Setup'
        uses: google-github-actions/setup-gcloud@v0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.2

      - id: init
        name: 'Terraform Init'
        run: terraform init

      - id: apply
        name: 'Terraform Apply'
        run: terraform apply -auto-approve -lock-timeout=60s

      - uses: actions/github-script@v3
        if: github.event_name == 'push'
        env:
          APPLY: "module.project_creation.google_project.project: Creation complete after 23s [id=projects/interview-73c6536fda778a65]"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            PROJECT=$(echo $APPLY | grep "module.project_creation.google_project.project: Creation complete" | grep -o 'interview-.*') 
            Project ID: $PROJECT
            BigQuery: https://console.cloud.google.com/bigquery?project=${PROJECT}

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
            
        
